### ISSUE TITLE
Newsletters improvements & fixes

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-newsletters#487]
Master thread for [improvements to Newsletter plugin](https://newsprojectp2.wordpress.com/2021/04/16/email-newsletter-needs-assessment/).

## Scoped bugfixes & enhancements

- [x] Reusable blocks handling (PR https://github.com/Automattic/newspack-newsletters/pull/450)
- [ ] Share link in newsletter content (https://github.com/Automattic/newspack-newsletters/issues/349)
- [x] Custom styling (https://github.com/Automattic/newspack-newsletters/issues/417)
- [ ] Mailchimp - merge tags (https://github.com/Automattic/newspack-newsletters/issues/452)
- [ ] Mailchimp tag creation (https://github.com/Automattic/newspack-newsletters/issues/242)
- [ ] Mailchimp - segments support (https://github.com/Automattic/newspack-newsletters/issues/22)
- [x] Posts Inserter - "Read more" links (https://github.com/Automattic/newspack-newsletters/issues/296, closed by https://github.com/Automattic/newspack-newsletters/pull/456)
- [ ] Posts Inserter - post subtitle display
- [ ] Embeds support (https://github.com/Automattic/newspack-newsletters/issues/386)
- [x] Posts Inserter in reusable blocks (https://github.com/Automattic/newspack-newsletters/issues/451)
- [ ] Send test email feature - persist email address
- [x] **Bug**: background color not applied (PR https://github.com/Automattic/newspack-newsletters/pull/456)
- [ ] Generic/copy+paste markup (https://github.com/Automattic/newspack-newsletters/issues/470)

## Broader, unscoped features

- [ ] Support more Core blocks (e.g gallery, media & text, cover)
- [ ] Bulk private/public status change (https://github.com/Automattic/newspack-newsletters/issues/325)
- [ ] Support more fonts (same list as the onboarding one with by default matching the site) -- global setting
- [ ] Automated emails (e.g. recurring newsletter w/ latest posts; see also [Mailchimp's automation docs](https://mailchimp.com/help/classic-automation-types/))
- [ ] ESP Analytics in the plugin
